#!/usr/bin/env bash

#
# Execute inline APEX code
#
# USAGE
#
#    sf-apex "CODE"                           # execute CODE
#    sf-apex -o ORG                           # execute Apex Code on ORG
#
# EXAMPLES
#
#    sf apex run                                                  # execute Anonymous Apex code in REPL, execute with CTRL+D
#    sf apex run -f file.apex                                     # execute a local Apex file
#    sf-apex "System.debug('Hello, Salesforce CLI');"
#    sf-apex "delete[SELECT Id FROM ErrorLog__c];"
#

yesno() {
  echo ""
  read -r -p "$1 [Y/n] " response
  [[ $response == "n" || $response == "N" ]] && exit 1
}

show_help() {
  # shellcheck disable=SC2086
  awk '/^[^ #]/{c=1}c==0{print $0}' $0 | sed -n '/^#/p' | sed 1d | sed 's/^#/ /g' \
    | perl -pe "s/ #(.*)$/$(tput setaf 0)\1$(tput sgr 0)/" \
    | perl -pe "s/(USAGE|EXAMPLES|COMMANDS)/$(tput setaf 0)\1$(tput sgr 0)/" \
    | perl -pe "s/\`(.+)\`/$(tput sgr 0 1)\1$(tput sgr 0)/"
  exit 1
}

setTargetOrg() {
  if [[ -z "$org" ]]; then
    org=$(cat .sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
  fi
  if [[ -z "$org" ]]; then
    org=$(cat ~/.sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
  fi
  if [[ -z "$org" ]]; then
    echo -e >&2 "\n $(tput setaf 1)Missing target org$(tput sgr 0)\n\n   Either provide with $(tput setaf 0)-o$(tput sgr 0) option, or set via $(tput setaf 0)sf config set target-org <org>$(tput sgr 0)"
    exit 1
  fi
}

org=""
code=""
codefile=$(mktemp)

while [ $# -gt 0 ]; do
  case $1 in
    -o|--org)
      shift
      org=$1
      ;;
    -h|--help)
      show_help
      ;;
    *)
      code=${1:-""}
      ;;
  esac
  shift
done
setTargetOrg
[[ "$org" == "production" ]] && echo -e >&2 "\n $(tput setaf 1)DO NOT RUN ON PRODUCTION!$(tput sgr 0)" && exit 1

if [ "${code}" ]; then
  [[ $DEBUG == "1" ]] && echo -e "\n   $(tput setaf 0)sf apex run -f ${codefile} -o ${org}$(tput sgr0)\n"
  yesno " Execute Apex code $(tput setaf 0)${code}$(tput sgr0) on $(tput setaf 1)${org}$(tput sgr0) ?"
  echo "${code}" > "$codefile"
  sf apex run -f "$codefile" -o "$org" >/dev/null
  exit 0
fi
