#!/usr/bin/env bash

#
# Inspect local custom-labels and profiles to identify inconsistencies
#
# USAGE
#
#     sf-inspect --labels             # list custom-labels on local metadata, package-manifest, translation-files and usage
#     sf-inspect --profiles           # compare profile settings
#     sf-inspect -d DIR               # save generated csv file in DIR folder [default: .data]
#

yesno() {
  echo ""
  read -p "$1 [Y/n] " response
  [[ $response == "n" || $response == "N" ]] && exit 1
}

show_help() {
  awk '/^[^ #]/{c=1}c==0{print $0}' $0 | sed -n '/^#/p' | sed 1d | sed 's/^#/ /g' \
    | perl -pe "s/ #(.*)$/$(tput setaf 0)\1$(tput sgr 0)/" \
    | perl -pe "s/(USAGE|EXAMPLES|COMMANDS)/$(tput setaf 0)\1$(tput sgr 0)/" \
    | perl -pe "s/\`(.+)\`/$(tput sgr 0 1)\1$(tput sgr 0)/"
  exit 1
}

target=".data"
labels=false
profiles=false

[[ -z "$1" ]] && show_help
[ ! -f "./sfdx-project.json" ] && echo >&2 "not a SFDX project!" && exit 1

while [ $# -gt 0 ]; do
  case $1 in
    -d)
      shift
      target=$1
      ;;
    -l|--labels)
      labels=true
      ;;
    -p|--profiles)
      profiles=true
      ;;
    -h|--help)
      show_help
      ;;
    *)
      ;;
  esac
  shift
done
mkdir -p "$target"

if [[ $labels == true ]]; then
  labelsfile="${target}/labels.csv"
  echo "\"Label\",\"en_US\"" > "$labelsfile"
  cat force-app/main/default/labels/CustomLabels.labels-meta.xml \
    | sed "s#&quot;#'#g" \
    | sed "s#\"#'#g" \
    | xml sel -N sf="http://soap.sforce.com/2006/04/metadata" \
        -t -m "//sf:labels" \
        --var linebreak -n --break \
        -o "\"" -v "sf:fullName/text()" -o "\",\"" -v "translate(sf:value/text(), \$linebreak , ' ')" -o "\"" -n \
    >> "$labelsfile"

  while read -r path; do
    file="$(basename $path)"
    lang="${file%%.*}"
    translationsfile="${target}/translation_${lang}.csv"
    echo "\"Label\",\"${lang}\"" > "${translationsfile}"
    cat "$path" \
      | sed "s#&quot;#'#g" \
      | sed "s#\"#'#g" \
      | xml sel -N sf="http://soap.sforce.com/2006/04/metadata" \
        -t -m "//sf:customLabels" \
        --var linebreak -n --break \
        -o "\"" -v "sf:name/text()" -o "\",\"" -v "translate(sf:label/text(), \$linebreak, ' ')" -o "\"" -n \
      >> "$translationsfile"
    csvtk join -l -f 1 "$labelsfile" "$translationsfile" --outer-join > temp; mv temp "$labelsfile"
    rm "$translationsfile"
  done < <(fd -e xml . force-app/main/default/translations -E '*en_US*')

  manifestfile="${target}/manifest.csv"
  echo "\"Label\",\"Manifest\"" > "$manifestfile"
  cat manifest/package.xml \
    | xml sel -N sf="http://soap.sforce.com/2006/04/metadata" \
        -t -m "//sf:types[sf:name='CustomLabel']" \
        -v "sf:members/text()" -n \
    | sed "s/$/,X/g" \
    >> "$manifestfile"
  csvtk join -l -f 1 "$labelsfile" "$manifestfile" --outer-join > temp; mv temp "$labelsfile"
  rm "$manifestfile"

  usagefile="${target}/usage.csv"
  echo "\"Label\",\"Usage\"" > "$usagefile"
  while read label; do
    echo "${label},$(rg -g '!{force-app/main/default/translations/*,force-app/main/default/labels/*}' -l -w ${label} force-app | wc -l | tr -d ' ')" >> "$usagefile"
  done < <(csvtk cut -f "Label" "$labelsfile" | sed 1d)
  csvtk join -l -f 1 "$labelsfile" "$usagefile" --outer-join > temp; mv temp "$labelsfile"
  rm "$usagefile"

  vd "$labelsfile"
fi

if [[ $profiles == true ]]; then
  echo "TODO"
fi

exit 0
