#!/usr/bin/env bash

#
# turn on trace debugging
#
# USAGE
#
#     sf-log -o ALIAS                 # enable trace logging for 24 hours on ALIAS org
#

setTargetOrg() {
  if [[ -z "$org" ]]; then
    org=$(cat .sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
  fi
  if [[ -z "$org" ]]; then
    org=$(cat ~/.sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
  fi
  if [[ -z "$org" ]]; then
    echo -e >&2 "\n $(tput setaf 1)Missing target org$(tput sgr 0)\n\n   Either provide with $(tput setaf 0)-o$(tput sgr 0) option, or set via $(tput setaf 0)sf config set target-org <org>$(tput sgr 0)"
    exit 1
  fi
}

org=""

while [ $# -gt 0 ]; do
  case $1 in
    -o)
      shift
      org=$1
      ;;
    -h|--help)
      cat $0 | sed -n '/^#/p' | sed '/^##/d' | sed 1d | sed 's/^#/ /g' \
        | perl -pe "s/ #(.*)$/$(tput setaf 0)\1$(tput sgr 0)/" \
        | perl -pe "s/(USAGE|EXAMPLES)/$(tput setaf 0)\1$(tput sgr 0)/"
      exit 1
      ;;
    *)
      ;;
  esac
  shift
done
setTargetOrg

now=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
exp=`date -v+24H -u +"%Y-%m-%dT%H:%M:%SZ"`
username=`sf org display -o ${org} --json | jq -r '.result.username'`
userid=`sf data query -q "SELECT id from USER where Username='${username}'" -o ${org} --json | jq -r '.result.records[].Id'`
traceid=`sf data query -q "SELECT Id FROM Traceflag WHERE TracedEntityId IN (SELECT ID from User WHERE ID = '${userid}')" -t -o ${org} --json | jq -r '.result.records[].Id'`

sf data update record -s TraceFlag -i ${traceid} -v "StartDate=${now} ExpirationDate=${exp}" -t
