#!/usr/bin/env bash

#
# USAGE
#
#    sf-metadata -o ALIAS                  # retrieve metadata from ALIAS org [default: b2bdev2]
#    sf-metadata                           # retrieve all metadata
#    sf-metadata -m NAME1 -m NAME2         # retrieve metadata for NAME1 and NAME2
#    sf-metadata -x                        # retrieve metadata based on manifest/package.xml
#

org="b2bdev2"
name=""
names_list=$(mktemp)

yesno() {
  echo ""
  read -p "$1 [Y/n] " response
  [[ $response == "n" || $response == "N" ]] && exit 1
}

while [ $# -gt 0 ]; do
  case $1 in
    -o)
      shift
      org=$1
      ;;
    -m)
      shift
      if [[ $name == "" ]]; then
        name=$1
      else
        name="${name},${1}"
      fi
      ;;
    -h)
      cat $0 | sed -n '/^#/p' | sed '/^##/d' | sed 1d | sed 's/^#/ /g' \
        | perl -pe "s/ #(.*)$/$(tput setaf 0)\1$(tput sgr 0)/" \
        | perl -pe "s/(USAGE|EXAMPLES)/$(tput setaf 8)\1$(tput sgr0)/"
      exit 1
      ;;
    *)
      ;;
  esac
  shift
done

if [[ $name == "" ]]; then
  name="all"
  yesno " Fetch $(tput setaf 4)${name}$(tput sgr0) metadata from $(tput setaf 1)${org}$(tput sgr0) ?"
else
  names=$(echo ${name} | perl -pe "s/,/, /g" | perl -pe "s/(\w+)/$(tput setaf 4)\1$(tput sgr0)/g")
  yesno " Fetch metadata ${names} from $(tput setaf 1)${org}$(tput sgr0) ?"
fi

if [[ $name == "all" ]]; then
  sfdx org list metadata-types -o ${org} \
    | jq -r '.metadataObjects[].xmlName' \
    | sed /ProcessFlowMigration/d \
    | sed /EventRelayConfig/d \
    | sed /ExperienceContainer/d \
    | sed /SearchCustomization/d \
    | sed /RegisteredExternalService/d \
    | sed /PortalDelegablePermissionSet/d \
    > ${names_list}
else
  echo ${name} | tr -d ' ' | tr ',' '\n' > ${names_list}
fi

total=$(cat ${names_list} | wc -l | tr -d ' ')
c=0
while read n; do
  c=$((c+1))
  echo -e "\n $(tput setaf 8)[${c}/${total}]$(tput sgr0) $(tput setaf 4)${n}$(tput sgr0):"
  sfdx project retrieve start -o ${org} -m ${n} > /dev/null
done < <(cat ${names_list})

