#!/usr/bin/env bash

#
# Get sObject information
#
# USAGE
#
#     sf-object -k KEY             # get entity definition for a key-prefix
#
# EXAMPLES
#
#     sf-object -k 001
#     sf-data -v EntityDefinition
#
# COMMANDS
#
#     sf data query -t -q "SELECT Label, QualifiedApiName FROM EntityDefinition WHERE KeyPrefix='001'"
#

yesno() {
  echo ""
  read -p "$1 [Y/n] " response
  [[ $response == "n" || $response == "N" ]] && exit 1
}

show_help() {
  awk '/^[^ #]/{c=1}c==0{print $0}' $0 | sed -n '/^#/p' | sed 1d | sed 's/^#/ /g' \
    | perl -pe "s/ #(.*)$/$(tput setaf 0)\1$(tput sgr 0)/" \
    | perl -pe "s/(USAGE|EXAMPLES|COMMANDS)/$(tput setaf 0)\1$(tput sgr 0)/" \
    | perl -pe "s/\`(.+)\`/$(tput sgr 0 1)\1$(tput sgr 0)/"
  exit 1
}

key=""

[[ -z "$1" ]] && show_help

while [ $# -gt 0 ]; do
  case $1 in
    -k|--key)
      shift
      key=$1
      ;;
    -h|--help)
      show_help
      ;;
    *)
      ;;
  esac
  shift
done

if [ -n "$key" ]; then
  echo
  sf data query -t -q "SELECT Label, QualifiedApiName FROM EntityDefinition WHERE KeyPrefix='${key}'" --json \
    | jq -r '.result.records[] | " \u001b[0;32m'"${key}"':\u001b[0m \(.Label) \u001b[30m(API: \(.QualifiedApiName))\u001b[0m"'
  [ -z "$key" ] && echo -e >&2 "\n $(tput setaf 1)Object key is missing$(tput sgr0)" && exit 1
  exit 0
fi

exit 0
