#!/usr/bin/env bash

_sfdata_completions() {
    local cur prev names
    cache="/tmp/sf-data.sobjects"
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [ ! -s "${cache}" ]; then
      org=$(cat .sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
      if [[ -z "$org" ]]; then
        org=$(cat ~/.sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
      fi
      sf sobject list -o ${org} -s all | paste -sd' ' - > ${cache}
    fi
    names=$(cat ${cache})

    case "${prev}" in
        -s|-v)
            COMPREPLY=($(compgen -W "${names}" -- ${cur}))
            return 0
            ;;
    esac
}

complete -F _sfdata_completions sf-data
