#!/usr/bin/env bash

# to prune cached sobjects:
#
#     make prune

_sfdata_completions() {
    local cur prev opts orgs
    cache="sf-data.sobjects"
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts="-a -b -c"

    if [ ! -f "${cache}" ]; then
      sfdx sobject list -o b2bdev1 -s all | paste -sd' ' - > ${cache}
    fi
    orgs=$(cat ${cache})

    case "${prev}" in
        -b)
            COMPREPLY=($(compgen -W "${orgs}" -- ${cur}))
            return 0
            ;;
        *)
            COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
            return 0
            ;;
    esac
}

complete -F _sfdata_completions sf-data
