#!/usr/bin/env bash

_sfdeploy_completions() {
    local cur prev alias
    cache="/tmp/sf-metadata.sobjects"
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [ ! -s "${cache}" ]; then
      org=$(cat .sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
      if [[ -z "$org" ]]; then
        org=$(cat ~/.sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
      fi
      sf org list metadata-types -o ${org} | jq -r '.metadataObjects[].xmlName' | paste -sd' ' - > ${cache}
    fi
    names=$(cat ${cache})
    alias=$(cat ~/.sfdx/alias.json | jq -r '.orgs | keys[]')

    case "${prev}" in
        -o)
            COMPREPLY=($(compgen -W "${alias}" -- ${cur}))
            return 0
            ;;
        -m)
            COMPREPLY=($(compgen -W "${names}" -- ${cur}))
            return 0
            ;;
    esac
}

complete -F _sfdeploy_completions sf-deploy

