#!/usr/bin/env bash

_sfdata_completions() {
    local cur prev orgs
    cache="/tmp/sf-data.sobjects"
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [ ! -f "${cache}" ]; then
      org=$(sf config get target-org --json | jq -r '.result[].value')
      sf sobject list -o ${org} -s all | paste -sd' ' - > ${cache}
    fi
    orgs=$(cat ${cache})

    case "${prev}" in
        -s|-v)
            COMPREPLY=($(compgen -W "${orgs}" -- ${cur}))
            return 0
            ;;
    esac
}

complete -F _sfdata_completions sf-data
