#!/usr/bin/env bash

_sflog_completions() {
    local cur prev alias
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local org=$(cat .sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
    if [[ -z "$org" ]]; then
      org=$(cat ~/.sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
    fi
    for i in "${!COMP_WORDS[@]}"; do
      if [[ "${COMP_WORDS[$i]}" = "-o" ]]; then
        org=${COMP_WORDS[$((i+1))]}
        break
      fi
    done

    COMPREPLY=($(compgen -W "-o -u -l -t -h --list --delete" -- ${cur}))
    case "${prev}" in
        -o)
            alias=$(cat ~/.sfdx/alias.json | jq -r '.orgs | keys[]')
            COMPREPLY=($(compgen -W "${alias}" -- ${cur}))
            return 0
            ;;
        -u)
            usercache="/tmp/sf-users-${org}"
            if [ ! -s "${usercache}" ]; then
              sf data query -q "SELECT username FROM User WHERE isActive=True" -o ${org} --json | jq -r '.result.records[].Username' > ${usercache}
            fi
            users=$(cat ${usercache})
            COMPREPLY=($(compgen -W "${users}" -- ${cur}))
            return 0
            ;;
        -l)
            levelcache="/tmp/sf-debuglevels-${org}"
            if [ ! -s "${levelcache}" ]; then
              sf data query -q "SELECT Id, DeveloperName, MasterLabel FROM DebugLevel" -t -o ${org} --json | jq -r '.result.records[].DeveloperName' > ${levelcache}
            fi
            level=$(cat ${levelcache})
            COMPREPLY=($(compgen -W "${level}" -- ${cur}))
            return 0
            ;;
    esac
}

complete -F _sflog_completions sf-log

