#!/usr/bin/env bash

_sfmetadata_completions() {
    local cur prev names
    cache="/tmp/sf-metadata.sobjects"
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [ ! -f "${cache}" ]; then
      org=$(sfdx config get target-org --json | jq -r '.result[].value')
      sfdx org list metadata-types -o ${org} | jq -r '.metadataObjects[].xmlName' | paste -sd' ' - > ${cache}
    fi
    names=$(cat ${cache})

    case "${prev}" in
        -m)
            COMPREPLY=($(compgen -W "${names}" -- ${cur}))
            return 0
            ;;
    esac
}

complete -F _sfmetadata_completions sf-metadata
