#!/usr/bin/env bash

_sfmetadata_completions() {
    local cur prev names alias
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    cache="/tmp/sf-metadata.sobjects"

    COMPREPLY=($(compgen -W "-o -m -x -p -h" -- ${cur}))
    case "${prev}" in
        -o)
            alias=$(cat ~/.sfdx/alias.json | jq -r '.orgs | keys[]')
            COMPREPLY=($(compgen -W "${alias}" -- ${cur}))
            return 0
            ;;
        -m)
            if [ ! -s "${cache}" ]; then
              org=$(cat .sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
              if [[ -z "$org" ]]; then
                org=$(cat ~/.sf/config.json 2>/dev/null | jq -r '."target-org" | select( . != null )')
              fi
              sf org list metadata-types -o ${org} | jq -r '.metadataObjects[].xmlName' | paste -sd' ' - > ${cache}
            fi
            names=$(cat ${cache})
            COMPREPLY=($(compgen -W "${names}" -- ${cur}))
            return 0
            ;;
    esac
}

complete -F _sfmetadata_completions sf-metadata
