#!/usr/bin/env bash

_sfobject_completions() {
    local cur prev alias
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    COMPREPLY=($(compgen -W "-h -k --key" -- ${cur}))
}

complete -F _sfobject_completions sf-object

