#!/usr/bin/env bash

_sfscratch_completions() {
    local cur prev names scratch
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    scratch=$(cat ~/.sfdx/alias.json | jq -r '.orgs | with_entries(select(.key | match("^scratch[0-9]+"))) | keys[]')

    case "${prev}" in
        --delete)
            COMPREPLY=($(compgen -W "${scratch}" -- ${cur}))
            return 0
            ;;
    esac
}

complete -F _sfscratch_completions sf-scratch

